# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check
        with:
          # A list of files, rockspecs, or directories to be checked. Paths can be
          # absolute or relative to the `path` option.
          files: 'test.lua'

          # The working directory for luacheck. The file list should be relative to
          # this path and output filenames be displayed relative to this path.
          # Default: ${{ github.workspace }}
          path: '${{ github.workspace }}'

          # Additional command-line arguments.
          # See https://luacheck.readthedocs.io/en/stable/cli.html
          args: ''

          # URL to a custom configuration (`.luacheckrc`) file that will be used as
          # the default configuration file.
          config: ''

          # Emits annotations for source code at locations parsed from the output.
          # Must be set to "none", "warning" or "error".
          #
          # Requires that output of warnings not be suppressed through the -qq or -qqq arguments.
          #
          # Default: 'none'
          annotate: 'test123'
